services:
  api-catalog:
    container_name: api-catalog
    image: api-catalog-img
    build:
      context: ./microservices/catalogservice
      dockerfile: Dockerfile
    ports:
      - "5097:8080"
    networks:
      - shop-network

  api-order:
    container_name: api-order
    image: api-order-img
    build:
      context: ./microservices
      dockerfile: ./orderservice/Dockerfile
    ports:
      - "5096:8080"
    networks:
      - shop-network
    environment:
      - ConnectionStrings__ServiceBus=Endpoint=empty
      - ASPNETCORE_ENVIRONMENT=Development
      - SagaSubscriptionOptions__SagaSubscriptions__0__Topic=ordertopic
      - SagaSubscriptionOptions__SagaSubscriptions__0__Subscription=order-subscription-all
      - SagaSubscriptionOptions__SagaSubscriptions__1__Topic=inventorytopic
      - SagaSubscriptionOptions__SagaSubscriptions__1__Subscription=inventory-sub-response
      - SagaSubscriptionOptions__SagaSubscriptions__2__Topic=paymenttopic
      - SagaSubscriptionOptions__SagaSubscriptions__2__Subscription=payment-sub-response
      - SagaSubscriptionOptions__SagaSubscriptions__3__Topic=shippingtopic
      - SagaSubscriptionOptions__SagaSubscriptions__3__Subscription=shipping-sub-response

      
  api-basket:
    container_name: api-basket
    image: api-basket-img
    build:
      context: ./microservices/basketservice
      dockerfile: Dockerfile
    ports:
      - "5095:8080"
    networks:
      - shop-network

  inventory-service:
    container_name: inventory-service
    image: inventory-service-img
    build:
      context: ./microservices
      dockerfile: ./inventoryservice/Dockerfile
    networks:
      - shop-network
    environment:
     - ConnectionStrings__ServiceBus=Endpoint=empty
     - Topics__Inventory=inventorytopic
     - ASPNETCORE_ENVIRONMENT=Development


  payment-service:
    container_name: payment-service
    image: payment-service-img
    build:
      context: ./microservices
      dockerfile: ./paymentservice/Dockerfile
    networks:
      - shop-network
    environment:
     - ConnectionStrings__ServiceBus=Endpoint=empty
     - Topics__Payment=paymenttopic
     - ASPNETCORE_ENVIRONMENT=Development

  shipping-service:
    container_name: shipping-service
    image: shipping-service-img
    build:
      context: ./microservices
      dockerfile: ./shippingservice/Dockerfile
    networks:
      - shop-network
    environment:
     - ConnectionStrings__ServiceBus=Endpoint=empty
     - Topics__Shipping=shippingtopic
     - ASPNETCORE_ENVIRONMENT=Development


  api-gateway:
    container_name: api-gateway
    image: api-gateway-img
    build:
      context: apigateway
      dockerfile: Dockerfile
    ports:
      - "5090:8080"
    networks:
      - shop-network
    depends_on:
      - api-catalog
      - api-order
      - api-basket

  eshop:
    container_name: eshop
    image: eshop-app-img
    build:
      context: eshop
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    networks:
      - shop-network
    depends_on:
      - api-gateway
    environment:
      - API_GATEWAY_URL=http://api-gateway:8080
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  shop-network:
    driver: bridge