
services:
  api-catalog:
    image: api-catalog-img
    container_name: api-catalog
    ports:
      - "5097:8080"
    networks:
      - shop-network

  api-order:
    image: api-order-img
    container_name: api-order
    networks:
      - shop-network

  api-gateway:
    image: api-gateway-img
    container_name: api-gateway
    ports:
      - "5096:8080"
    networks:
      - shop-network
    depends_on:
      - api-catalog
      - api-order

  eshop:
    build:
      context: ./eshop
    container_name: eshop
    ports:
      - "5000:80"           # Esponi la web app su localhost:5000
    networks:
      - shop-network
    depends_on:
      - api-gateway

networks:
  shop-network:
    driver: bridge
