
services:
  api-catalog:
    image: api-catalog-img
    container_name: api-catalog
    ports:
      - "5097:8080"
    networks:
      - shop-network

  api-order:
    image: api-order-img
    container_name: api-order
    ports:
      - "5096:8080"
    networks:
      - shop-network

  api-gateway:
    image: api-gateway-img
    container_name: api-gateway
    ports:
      - "5090:8080"
    networks:
      - shop-network
    depends_on:
      - api-catalog
      - api-order

  eshop:
    image: eshop-app-img
    container_name: eshop
    ports:
      - "5050:8080"
    networks:
      - shop-network
    depends_on:
      - api-gateway
    environment:
      - API_GATEWAY_URL=http://api-gateway:8080
networks:
  shop-network:
    driver: bridge
