# @ApiGateway_HostAddress = http://localhost:5096

# GET {{ApiGateway_HostAddress}}/weatherforecast/
# Accept: application/json

# ###

#Invoke-RestMethod -Uri "http://localhost:5034/api/catalog/products" -Method Get
#Invoke-RestMethod -Uri "http://localhost:5096/api/catalog/products" -Method Get

